site_name: AI Service Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Domain:
    - Domain Services: domain_services.md
    - Domain Models: domain_models.md
  - External Services: external_services.md
  - Guides:
    - Quickstart: quickstart.md
  - Services and Routes: services_and_routes.md
  - Authentication: authentication.md
  - Middlewares: middlewares.md
  - Error Handling: error_handling.md
  - Resilient Execution: resilient_execution.md
  - Subscription and Payment: subscription_payment.md
  - CLI Commands: cli_commands.md
  - Improvement Tasks: tasks.md
